### ISSUE TITLE
No naked raw code on the repository. Can we get a open source code for learning development purposes?

### ISSUE THREAD

**Issue by NIRVANIAN472821** [Mytoolz/Email-Bomber#1]
Can we get the raw data or code as a learning Materials?

**Comment by Mytoolz** [comment]
No sorry we don't provide open source code.

**Comment by NIRVANIAN472821** [comment]
Oh damn, i was looking forward to get the modules or the code of this software as a thesis material (The thing that i really want the most is how do it send an email from an address without having an access into it **•[ In order/for the purpose of anti-phishing and security resistance research]•**). Please reconsider this sir, thank you. If there's in any way i can get the code or a Specific module that i want i would be glad to do anything for it. Thank you 💖.

**Comment by NIRVANIAN472821** [comment]
Closed in order for re-fresh issue reconsideration. Thank you 💖.
